### ISSUE TITLE
Onlyoffice 7.0

### ISSUE THREAD

**Issue by ndx1905-github** [Zegorax/OnlyOffice-Unlimited#12]
Looks like the new 7.0 release broke the fix ?

**Comment by woneal** [comment]
Looks like so...

**Comment by Zegorax** [comment]
See #4

**Comment by Practicalbutterfly5** [comment]
Add the following entry point to docker-compose file.

```

entrypoint: bash -c "sed -i 's/isSupportEditFeature=function(){return!1}/isSupportEditFeature=function(){return 1}/g'  /var/www/onlyoffice/documentserver/web-apps/apps/*/mobile/dist/js/app.js;/app/ds/run-document-server.sh;"

```
Only basic text editing is possible with this, but hey it’s something.

Don't forget the clear website date of your onlyoffice domain and clear data of the Nextcloud android app.
