### ISSUE TITLE
2023 not working for me

### ISSUE THREAD

**Issue by Redzzzzzzzzz** [Zegorax/OnlyOffice-Unlimited#14]
Hi, I have got the OnlyOffice DOCS installation on ubuntu 22.04 and use it with the nextcloud app. I kinda want to remove the connection limit and the mobile edit limitation but your script does not seem to do anything. 
Is it still possible in 2023? If yes can someone maybe guide me through how to do it? Ill be able to make an automated script for it then as well. 

Thanks in advance.

**Comment by RTechSn** [comment]
Yes, me too.

**Comment by makiavellye32** [comment]
I tried to use it too, but ran into a little difficulty
I slightly modified the script to use newer python version, but I get an error:
```
It will be placed automatically in the Data directory of OnlyOffice
Patching docservice and convert...
Traceback (most recent call last):
  File "/home/bain/OnlyOffice-Unlimited/index.py", line 71, in <module>
    f = open(basePath+file, 'wb')
OSError: [Errno 26] Text file busy: '/var/www/onlyoffice/documentserver/server/DocService/docservice'
Patching docservice and convert...
Done! Running Document Server...
```
And in the end the server says that the license has expired :(

**Comment by Zegorax** [comment]
See #4
