### ISSUE TITLE
Android apps not working

### ISSUE THREAD

**Issue by y0grt** [Zegorax/OnlyOffice-Unlimited#3]
Hi again.
Although online version works perfectly, Android app keeps on read-only mode.

Any idea?
Thank you.

**Comment by Zegorax** [comment]
Mobile apps are outside the scope of this project, since they are running their own DocumentServer inside of them.

**Comment by y0grt** [comment]
Correct.
Just realised that editing from Nextcloud app works perfectly, it happens only with Onlyoffice app.
They removed the feature since I've been able to use this before.
