### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ltnhuan** [Zegorax/OnlyOffice-Unlimited#8]
i install https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx

when run https://github.com/Zegorax/OnlyOffice-Unlimited 

the system still blocks 20 concurrent connections
 command run https://github.com/Zegorax/OnlyOffice-Unlimited/blob/master/install.sh is successful

**Comment by Zegorax** [comment]
Read #4
